Repository kakaotech-19/backend, pull requests merged in 2024-12, with the labels that each got.

#125 Feature/todak 260/무한 스크롤 API 정렬 기준 변경
  build.gradle
  src/main/java/com/heartsave/todaktodak_api/TodaktodakApiApplication.java
  src/main/java/com/heartsave/todaktodak_api/common/constant/CoreConstant.java
  src/main/java/com/heartsave/todaktodak_api/diary/controller/MySharedDiaryController.java
  src/main/java/com/heartsave/todaktodak_api/diary/controller/PublicDiaryController.java
  src/main/java/com/heartsave/todaktodak_api/diary/domain/DiaryPageIndex.java
  src/main/java/com/heartsave/todaktodak_api/diary/dto/PublicDiary.java
  src/main/java/com/heartsave/todaktodak_api/diary/dto/request/DiaryPageRequest.java
  src/main/java/com/heartsave/todaktodak_api/diary/dto/response/MySharedDiaryPaginationResponse.java
  src/main/java/com/heartsave/todaktodak_api/diary/dto/response/MySharedDiaryResponse.java
  src/main/java/com/heartsave/todaktodak_api/diary/dto/response/PublicDiaryPageResponse.java
  src/main/java/com/heartsave/todaktodak_api/diary/entity/PublicDiaryEntity.java
  src/main/java/com/heartsave/todaktodak_api/diary/entity/projection/DiaryPageIndexProjection.java
  src/main/java/com/heartsave/todaktodak_api/diary/entity/projection/MySharedDiaryContentProjection.java
  src/main/java/com/heartsave/todaktodak_api/diary/entity/projection/PublicDiaryContentProjection.java
  src/main/java/com/heartsave/todaktodak_api/diary/factory/DiaryPageIndexFactory.java
  src/main/java/com/heartsave/todaktodak_api/diary/repository/MySharedDiaryRepository.java
  src/main/java/com/heartsave/todaktodak_api/diary/repository/PublicDiaryRepository.java
  src/main/java/com/heartsave/todaktodak_api/diary/service/MySharedDiaryService.java
  src/main/java/com/heartsave/todaktodak_api/diary/service/PublicDiaryService.java
  src/test/java/com/heartsave/todaktodak_api/diary/controller/MySharedDiaryControllerTest.java
  src/test/java/com/heartsave/todaktodak_api/diary/controller/PublicDiaryControllerTest.java
  src/test/java/com/heartsave/todaktodak_api/diary/repository/DiaryRepositoryTest.java
  src/test/java/com/heartsave/todaktodak_api/diary/repository/MySharedDiaryRepositoryTest.java
  src/test/java/com/heartsave/todaktodak_api/diary/repository/PublicDiaryRepositoryTest.java
  src/test/java/com/heartsave/todaktodak_api/diary/service/MySharedDiaryServiceTest.java
  src/test/java/com/heartsave/todaktodak_api/diary/service/PublicDiaryServiceTest.java
Labels: 📦refactor

#127 Feature/todak 262/atomic past notification
  src/main/java/com/heartsave/todaktodak_api/common/security/component/AuthenticationEntryPointImpl.java
  src/main/java/com/heartsave/todaktodak_api/common/security/component/jwt/JwtValidationFilter.java
  src/main/java/com/heartsave/todaktodak_api/common/security/config/SecurityConfig.java
  src/main/java/com/heartsave/todaktodak_api/event/controller/SseEventController.java
  src/main/java/com/heartsave/todaktodak_api/event/repository/SseEmitterRepository.java
  src/main/java/com/heartsave/todaktodak_api/event/service/SseEventService.java
  src/main/java/com/heartsave/todaktodak_api/event/service/SseManager.java
  src/main/resources/application.yaml
  src/test/java/com/heartsave/todaktodak_api/event/repository/SseEmitterRepositoryTest.java
  src/test/java/com/heartsave/todaktodak_api/event/service/SseEventServiceSuccessTest.java
  src/test/java/com/heartsave/todaktodak_api/event/service/SseManagerTest.java
Labels: 🛠️fix, 📦refactor, 🏗️config

#128 Feature/todak 272/ Instant와 locale 정보를 활용한 데이터 조회 로직 구성
  src/main/java/com/heartsave/todaktodak_api/ai/client/dto/request/ClientBgmRequest.java
  src/main/java/com/heartsave/todaktodak_api/ai/client/dto/request/ClientWebtoonRequest.java
  src/main/java/com/heartsave/todaktodak_api/common/constant/CoreConstant.java
  src/main/java/com/heartsave/todaktodak_api/common/converter/InstantConverter.java
  src/main/java/com/heartsave/todaktodak_api/common/converter/InstantUtils.java
  src/main/java/com/heartsave/todaktodak_api/diary/controller/DiaryController.java
  src/main/java/com/heartsave/todaktodak_api/diary/controller/MySharedDiaryController.java
  src/main/java/com/heartsave/todaktodak_api/diary/controller/PublicDiaryController.java
  src/main/java/com/heartsave/todaktodak_api/diary/dto/request/DiaryWriteRequest.java
  src/main/java/com/heartsave/todaktodak_api/diary/dto/response/DiaryYearMonthResponse.java
  src/main/java/com/heartsave/todaktodak_api/diary/entity/DiaryEntity.java
  src/main/java/com/heartsave/todaktodak_api/diary/entity/PublicDiaryEntity.java
  src/main/java/com/heartsave/todaktodak_api/diary/entity/projection/DiaryYearMonthProjection.java
  src/main/java/com/heartsave/todaktodak_api/diary/repository/DiaryRepository.java
  src/main/java/com/heartsave/todaktodak_api/diary/repository/MySharedDiaryRepository.java
  src/main/java/com/heartsave/todaktodak_api/diary/service/DiaryService.java
  src/main/java/com/heartsave/todaktodak_api/diary/service/MySharedDiaryService.java
  src/test/java/com/heartsave/todaktodak_api/ai/webhook/controller/AiWebhookControllerTest.java
  src/test/java/com/heartsave/todaktodak_api/ai/webhook/repository/AiRepositoryTest.java
  src/test/java/com/heartsave/todaktodak_api/diary/common/TestDiaryObjectFactory.java
  src/test/java/com/heartsave/todaktodak_api/diary/controller/DiaryControllerTest.java
  src/test/java/com/heartsave/todaktodak_api/diary/repository/DiaryRepositoryTest.java
  src/test/java/com/heartsave/todaktodak_api/diary/repository/MySharedDiaryRepositoryTest.java
  src/test/java/com/heartsave/todaktodak_api/diary/service/DiaryServiceTest.java
  src/test/java/com/heartsave/todaktodak_api/diary/service/MySharedDiaryServiceTest.java
Labels: ✨feature

#130 Feature/todak 281/utc logic modify
  src/main/java/com/heartsave/todaktodak_api/diary/controller/DiaryController.java
  src/main/java/com/heartsave/todaktodak_api/diary/dto/response/DiaryResponse.java
  src/main/java/com/heartsave/todaktodak_api/diary/repository/DiaryRepository.java
  src/main/java/com/heartsave/todaktodak_api/diary/repository/MySharedDiaryRepository.java
  src/main/java/com/heartsave/todaktodak_api/diary/repository/PublicDiaryRepository.java
  src/main/java/com/heartsave/todaktodak_api/diary/service/DiaryService.java
  src/test/java/com/heartsave/todaktodak_api/diary/controller/DiaryControllerTest.java
  src/test/java/com/heartsave/todaktodak_api/diary/repository/DiaryRepositoryTest.java
  src/test/java/com/heartsave/todaktodak_api/diary/repository/MySharedDiaryRepositoryTest.java
  src/test/java/com/heartsave/todaktodak_api/diary/service/DiaryServiceTest.java
Labels: 🛠️fix, 📦refactor, 🧪test

#132 Feature/todak 287/diary webhook ip
  src/main/java/com/heartsave/todaktodak_api/ai/client/dto/request/ClientAiCommentRequest.java
  src/main/java/com/heartsave/todaktodak_api/ai/client/dto/request/ClientBgmRequest.java
  src/main/java/com/heartsave/todaktodak_api/ai/client/dto/request/ClientCharacterRequest.java
  src/main/java/com/heartsave/todaktodak_api/ai/client/dto/request/ClientIPInfo.java
  src/main/java/com/heartsave/todaktodak_api/ai/client/dto/request/ClientWebtoonRequest.java
  src/main/java/com/heartsave/todaktodak_api/ai/client/service/AiClientService.java
  src/main/java/com/heartsave/todaktodak_api/ai/client/util/ClientIpUtil.java
  src/main/java/com/heartsave/todaktodak_api/common/config/TempEmbeddedRedisConfig.java
  src/test/java/com/heartsave/todaktodak_api/ai/util/ClientIPUtilTest.java
Labels: ✨feature

#134 feat: 공개 일기 삭제 API 작성 TODAK-289
  src/main/java/com/heartsave/todaktodak_api/common/exception/errorspec/PublicDiaryErrorSpec.java
  src/main/java/com/heartsave/todaktodak_api/common/storage/s3/S3FileStorageManager.java
  src/main/java/com/heartsave/todaktodak_api/diary/controller/MySharedDiaryController.java
  src/main/java/com/heartsave/todaktodak_api/diary/service/MySharedDiaryService.java
  src/test/java/com/heartsave/todaktodak_api/diary/repository/DiaryRepositoryTest.java
  src/test/java/com/heartsave/todaktodak_api/diary/repository/PublicDiaryRepositoryTest.java
Labels: ✨feature

#136 Feature/todak 296/일기 작성시 장르 추가 및 IP 전달 변경
  src/main/java/com/heartsave/todaktodak_api/ai/client/dto/request/ClientAiCommentRequest.java
  src/main/java/com/heartsave/todaktodak_api/ai/client/dto/request/ClientBgmRequest.java
  src/main/java/com/heartsave/todaktodak_api/ai/client/dto/request/ClientCharacterRequest.java
  src/main/java/com/heartsave/todaktodak_api/ai/client/dto/request/ClientDomainInfo.java
  src/main/java/com/heartsave/todaktodak_api/ai/client/dto/request/ClientIPInfo.java
  src/main/java/com/heartsave/todaktodak_api/ai/client/dto/request/ClientWebtoonRequest.java
  src/main/java/com/heartsave/todaktodak_api/ai/client/util/ClientDomainUrlUtil.java
  src/main/java/com/heartsave/todaktodak_api/diary/constant/DiaryBgmGenre.java
  src/main/java/com/heartsave/todaktodak_api/diary/dto/request/DiaryWriteRequest.java
  src/main/java/com/heartsave/todaktodak_api/diary/entity/DiaryEntity.java
  src/test/java/com/heartsave/todaktodak_api/ai/client/service/AiClientServiceTest.java
  src/test/java/com/heartsave/todaktodak_api/ai/util/ClientDomainUrlUtilTest.java
  src/test/java/com/heartsave/todaktodak_api/ai/webhook/repository/AiRepositoryTest.java
  src/test/java/com/heartsave/todaktodak_api/common/BaseTestObject.java
  src/test/java/com/heartsave/todaktodak_api/diary/controller/DiaryControllerTest.java
  src/test/java/com/heartsave/todaktodak_api/diary/service/DiaryServiceTest.java
Labels: ✨feature, 🧪test

#138 feat: Entity의 BGM 장르 필드 상수화
  src/main/java/com/heartsave/todaktodak_api/diary/entity/DiaryEntity.java
Labels: ✨feature

#140 캐릭터 화풍 선택
  src/main/java/com/heartsave/todaktodak_api/auth/repository/RefreshTokenCacheRepository.java
  src/main/java/com/heartsave/todaktodak_api/common/exception/errorspec/S3ErrorSpec.java
  src/main/java/com/heartsave/todaktodak_api/common/security/component/jwt/JwtLogoutFilter.java
  src/main/java/com/heartsave/todaktodak_api/common/security/component/jwt/JwtValidationFilter.java
  src/main/java/com/heartsave/todaktodak_api/common/security/config/SecurityConfig.java
  src/main/java/com/heartsave/todaktodak_api/common/storage/s3/S3FileStorageManager.java
  src/main/java/com/heartsave/todaktodak_api/diary/constant/DiaryCharacterStyle.java
  src/main/java/com/heartsave/todaktodak_api/member/controller/CharacterController.java
  src/main/java/com/heartsave/todaktodak_api/member/service/CharacterService.java
  src/test/java/com/heartsave/todaktodak_api/common/security/component/jwt/JwtLogoutFilterTest.java
  src/test/java/com/heartsave/todaktodak_api/common/storage/S3FileStorageManagerTest.java
Labels: 📦refactor

#142 OAuth2 인증 요청 정보 쿠키 전환
  src/main/java/com/heartsave/todaktodak_api/auth/service/AuthService.java
  src/main/java/com/heartsave/todaktodak_api/common/security/component/oauth2/CookieOauth2AuthorizationRequestRepository.java
  src/main/java/com/heartsave/todaktodak_api/common/security/config/SecurityConfig.java
  src/main/java/com/heartsave/todaktodak_api/common/security/util/CookieUtils.java
Labels: 🛠️fix, 📦refactor
